@extends('layouts.site')
@section('content')
  <div class="container">
    <h1>Terms of Use</h1>
    <p>Welcome to the <strong>{{ URL::to('/') }}</strong> website. This website belongs to {{ Config::get('site.business.name') }} ("{{ Config::get('site.app_name') }}") and is operated by {{ Config::get('site.app_name') }}. The information provided on this site is intended for general information purposes.</p>
    <p>Please read and review these Terms of Use carefully before accessing or using this website. By accessing or using this site, you acknowledge that you have read, understood and agreed to these Terms of Use. If you do not agree to the Terms of Use, you may not access or use the website. {{ Config::get('site.app_name') }} may alter these Terms of Use from time to time, so you should periodically check these Terms of Use as any changes will take effect as soon as they are posted to this website.</p>
     <ol>
      <li><strong>Use of Website.</strong> Your access to and use of the information contained in the website is subject to these Terms of Use. You agree to act lawfully at all times in using and accessing this website and you will not do anything which damages, interferes with, disrupts access to, interrupts or impairs the functionality of this website or inhibits other users’ use and enjoyment of the site.</li>
      <li><strong>Content.</strong> You agree that access to and use of this website and its content is at your own risk. {{ Config::get('site.app_name') }} may add, alter or delete materials from this website at any time at its discretion. {{ Config::get('site.app_name') }} will use reasonable efforts to include accurate and up-to-date information on this website but gives no warranties, undertakings or representations of any kind as to its accuracy, currency, quality, completeness or fitness for purpose and any information provided by {{ Config::get('site.app_name') }} and made available on this website is provided on an “as is” basis. {{ Config::get('site.app_name') }} disclaims all warranties, express or implied to the full extent permitted by law. Neither {{ Config::get('site.app_name') }}, its affiliates, nor any party involved in creating, producing or delivering this website shall be liable for any loss, damage or cost whatsoever, whether in contract, tort (including negligence) or otherwise arising from reliance on information contained in this website, access to, use of, or inability to use this website, or any errors or omissions in its content. This limitation includes any loss, damage or cost caused by any viruses that infect your computer equipment, software or data.</li>
      <li><strong>Privacy.</strong> {{ Config::get('site.app_name') }} respects the privacy of its website users. Please refer to our Privacy Statement which explains users' rights and the basis on which we may use any personal data (including by using “cookies”) that is disclosed to us via this website.</li>
      <li><strong>Third Party Websites and Links.</strong> This website may contain links or references to other websites maintained by third parties over whom we have no control. Such links are provided merely as a convenience. Similarly, this website may be accessed from third party links over which {{ Config::get('site.app_name') }} has no control. {{ Config::get('site.app_name') }} makes no warranties, undertakings or representations of any kind as to the accuracy, currency, quality, completeness or fitness for purpose of any information contained in such websites and shall have no liability for any loss, damage or cost of any kind arising from such information. Inclusion of any third party link does not imply an endorsement or recommendation by {{ Config::get('site.app_name') }}.</li>
      <li><strong>Medical Information.</strong> This website may contain information relating to various medical conditions and their treatment. This information is provided for general information only and is not meant to be a substitute for advice provided by a doctor or other qualified healthcare professional. You should not use the information in this website to diagnose a health or fitness problem or disease – always consult with a doctor or other qualified healthcare professional.</li>
      <li><strong>Non-Confidential Information.</strong> Subject to our Privacy Statement, any communication or other material that you send to {{ Config::get('site.app_name') }} through the internet or post on the website by electronic mail or otherwise, such as any questions, comments and suggestions, is and will be deemed to be non-confidential and {{ Config::get('site.app_name') }} shall have no obligation of any kind with respect to it. {{ Config::get('site.app_name') }} shall be free to use any ideas, concepts, know-how or techniques contained in these communications and materials for any purpose whatsoever, including but not limited to, developing, manufacturing and marketing products.</li>
      <li><strong>Intellectual Property Rights.</strong> {{ Config::get('site.app_name') }} owns all copyright, patents, database rights, trade marks, designs, know-how and confidential information (whether registered or not), and all other intellectual property rights existing in this website and its contents. The contents of this website may only be copied for non-commercial individual reference with all copyright or other proprietary notices retained, and thereafter may not be recopied, reproduced or otherwise redistributed. Except as expressly permitted above, you may not copy, display, download, distribute, modify, reproduce, republish or retransmit any information, text or documents contained in this website or any part of it in any electronic medium or in hard copy, or create any derivative work based on it, without {{ Config::get('site.app_name') }}’s express written consent. In addition, the {{ Config::get('site.app_name') }} name and logo are registered trademarks and may not be used without {{ Config::get('site.app_name') }}’s written permission. The misuse of {{ Config::get('site.app_name') }}’s trademarks or any other materials is prohibited and may be in breach of copyright law, trademark law and/or other Irish laws. Please note that {{ Config::get('site.app_name') }} actively and aggressively enforces its intellectual property rights to the fullest extent of the law.</li>
      <li><strong>Irish Laws.</strong> This website and its contents are intended to comply with Irish laws. Although the information on this website is accessible to users outside of the Republic of Ireland, the information on the website is intended for use only by residents of the Republic of Ireland. Other countries may have laws, regulatory requirements and medical practices that differ from those in the Republic of Ireland. These Terms of Use and your use of the website shall be governed by and construed in accordance with the laws of Ireland. The Irish courts shall have exclusive jurisdiction over any disputes arising in connection with this website.</li>
      <li><strong>Queries and Complaints.</strong> In the event you have a query or wish to raise a complaint you should contact {{ Config::get('site.app_name') }}, at:<br>
      <span class="text-muted">
        {{ Config::get('site.business.name') }},<br>
        {{ Config::get('site.business.address') }}<br>
      </span>
      and {{ Config::get('site.app_name') }} shall endeavour to answer or resolve any queries or complaints as quickly as possible.</li>
      <li><strong>Miscellaneous.</strong> To the extent that any provisions of these Terms of Use are held to be illegal, invalid or unenforceable, then such provisions shall be severed and deleted without affecting the enforceability of the remaining provisions.</li>
    </ol>
  </div>
@stop
